name: 'voiceos'
version: '0.8.0'
description: 'VoiceOS Flutter SDK'
homepage: 'https://voiceos.io'
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  collection: '^1.17.0'
  http: '>=0.13.0 <0.14.0'
  intl: any
  meta: '^1.1.8'
dev_dependencies:
  test: '>=1.21.6 <1.22.0'
